### ISSUE TITLE
Refactor: Extract error enhancers from crud-error-handlers.ts

### ISSUE THREAD

**Issue by kesslerio** [kesslerio/attio-mcp-server#1001]
## Summary

`src/handlers/tool-configs/universal/core/crud-error-handlers.ts` is **1156 lines** - well over the 500-line guideline from CLAUDE.md. The `handleCreateError` (131 lines) and `handleUpdateError` (127 lines) functions both exceed the 30-40 line function guideline and use sequential if-else chains for error pattern matching.

## Current State

Both handlers follow the same pattern:
1. Check for required fields error → enhance
2. Check for uniqueness/duplicate error → enhance  
3. Check for attribute-not-found error → enhance
4. Check for complex type error → enhance
5. Check for select/status error → enhance
6. Check for record-reference error → enhance
7. Fallback to generic error

This sequential pattern is repeated in both functions with slight variations.

### Option A: Strategy Map Pattern (Recommended)

Extract error enhancers to a composable pipeline:

```typescript
interface ErrorEnhancer {
  name: string;
  matches: (error: unknown, context: CrudErrorContext) => boolean;
  enhance: (error: unknown, context: CrudErrorContext) => Promise<string | null>;
  errorName: string;
}

const CREATE_ERROR_ENHANCERS: ErrorEnhancer[] = [
  requiredFieldsEnhancer,
  uniquenessEnhancer,
  attributeNotFoundEnhancer,
  complexTypeEnhancer,
  selectStatusEnhancer,
  recordReferenceEnhancer,
];

async function handleCreateError(error, resourceType, recordData) {
  const context = { operation: 'create', resourceType, recordData };
  
  for (const enhancer of CREATE_ERROR_ENHANCERS) {
    if (enhancer.matches(error, context)) {
      const enhanced = await enhancer.enhance(error, context);
      if (enhanced) {
        throw createErrorResult(enhanced, enhancer.errorName, { context });
      }
    }
  }
  
  // Fallback
  throw createErrorResult(genericMessage, 'create_error', { context });
}
```

### Option B: Extract to Separate Module

Move all `enhance*` functions to `src/handlers/tool-configs/universal/core/error-enhancers/`:
- `attribute-enhancer.ts` - attribute-not-found errors
- `uniqueness-enhancer.ts` - duplicate/uniqueness errors  
- `select-status-enhancer.ts` - select/status option errors
- `complex-type-enhancer.ts` - location, phone, personal-name errors
- `record-reference-enhancer.ts` - record reference format errors
- `index.ts` - re-exports and shared types

### Benefits

1. **SRP compliance** - Each enhancer has single responsibility
2. **Testability** - Enhancers can be unit tested independently
3. **Maintainability** - Adding new error patterns = adding new enhancer
4. **Reduced cognitive load** - Smaller, focused files
5. **Reusability** - Same enhancers work for create/update/delete

## Files Affected

| File | Action |
|------|--------|
| `src/handlers/tool-configs/universal/core/crud-error-handlers.ts` | Refactor to use enhancer pipeline |
| `src/handlers/tool-configs/universal/core/error-enhancers/` | New directory with extracted enhancers |

## Acceptance Criteria

- [ ] `crud-error-handlers.ts` reduced to <500 lines
- [ ] `handleCreateError` and `handleUpdateError` reduced to <50 lines each
- [ ] All existing tests pass unchanged
- [ ] No behavior changes (pure refactoring)
- [ ] Each enhancer has focused unit tests

## Related

- PR #1000 added Issue #990 uniqueness enhancement following existing style
- This is pre-existing tech debt, not introduced by #1000

**Comment by kesslerio** [comment]
@claude take to PR

**Comment by kesslerio** [comment]
# Complete Refactoring Guide: Lessons from PR #1048 Failure

PR #1048 attempted this refactoring but failed catastrophically with 80+ TypeScript compilation errors. This guide documents what went wrong and provides a detailed roadmap for doing it correctly.

---

## 🚨 What Went Wrong in PR #1048

### Root Cause: Missing Function Signatures

The refactoring removed **all function signatures** during extraction, leaving only function bodies:

**BROKEN CODE** (PR #1048):
```typescript
// attribute-enhancer.ts - INVALID
  const matrix: number[][] = [];  // ❌ No function declaration!
  for (let i = 0; i <= a.length; i++) {
    matrix[i] = [i];
  }
```

**CORRECT CODE**:
```typescript
// attribute-enhancer.ts - VALID
const levenshteinDistance = (a: string, b: string): number => {
  const matrix: number[][] = [];  // ✅ Function signature present
  for (let i = 0; i <= a.length; i++) {
    matrix[i] = [i];
  }
  return matrix[a.length][b.length];
};
```

### Specific Failures (80+ errors)

1. **Missing function declarations** - Every extracted function lost its signature
2. **Missing variable declarations** - Variables used without `const`/`let`/`var`
3. **Incomplete imports** - `CrudErrorContext`, `CREATE_ERROR_ENHANCERS` not imported
4. **Broken enhancer pipeline** - `enhancer.enhance()` called but result never captured

---

## ✅ The Correct Approach

### Target Architecture

```
src/handlers/tool-configs/universal/core/
├── crud-error-handlers.ts (400 lines - reduced from 1156)
└── error-enhancers/
    ├── types.ts (interface definitions)
    ├── index.ts (exports and pipelines)
    ├── attribute-enhancer.ts
    ├── select-status-enhancer.ts
    ├── complex-type-enhancer.ts
    ├── record-reference-enhancer.ts
    ├── uniqueness-enhancer.ts
    └── required-fields-enhancer.ts
```

### Strategy Pattern Interface

```typescript
// error-enhancers/types.ts
export interface CrudErrorContext {
  operation: 'create' | 'update' | 'delete' | 'search';
  resourceType: string;
  recordData?: Record<string, unknown>;
  recordId?: string;
  validationMetadata?: ValidationMetadata;
}

export interface ErrorEnhancer {
  name: string;
  matches: (error: unknown, context: CrudErrorContext) => boolean;
  enhance: (error: unknown, context: CrudErrorContext) => Promise<string | null>;
  errorName: string;
}
```

### Refactored Handler Pattern

```typescript
// crud-error-handlers.ts (simplified to ~50 lines)
export const handleCreateError = async (
  error: unknown,
  resourceType: string,
  recordData: Record<string, unknown>
): Promise<never> => {
  const context: CrudErrorContext = {
    operation: 'create',
    resourceType,
    recordData,
  };

  sanitizedLog(logger, 'error', 'Create operation failed', {
    resourceType,
    error: error instanceof Error ? error.message : String(error),
  });

  // Run through error enhancer pipeline
  for (const enhancer of CREATE_ERROR_ENHANCERS) {
    if (enhancer.matches(error, context)) {
      const enhanced = await enhancer.enhance(error, context);
      if (enhanced) {
        const resourceName = getSingularResourceType(resourceType as UniversalResourceType);
        throw createErrorResult(
          `Failed to create ${resourceName}: ${enhanced}`,
          enhancer.errorName,
          { context }
        );
      }
    }
  }

  // Fallback to generic error
  const resourceName = getSingularResourceType(resourceType as UniversalResourceType);
  const baseError = error instanceof Error ? error.message : String(error);
  const apiErrors = extractAttioValidationErrors(error);
  const attioMessage = extractAttioMessage(error);
  const errorMessage = apiErrors
    ? `${baseError}. Details: ${apiErrors}`
    : attioMessage ? `${baseError}. Details: ${attioMessage}` : baseError;

  throw createErrorResult(
    `Failed to create ${resourceName}: ${errorMessage}`,
    'create_error',
    { context, original: error }
  );
};
```

**Benefits**: Reduced from 131 lines to ~50 lines, extensible, testable, DRY

---

## 📋 Step-by-Step Implementation

### Phase 1: Setup (15 minutes)

```bash
git checkout main
git pull origin main
git checkout -b refactor/issue-1001-error-enhancers
mkdir -p src/handlers/tool-configs/universal/core/error-enhancers
touch src/handlers/tool-configs/universal/core/error-enhancers/{types,index}.ts
npm run test:offline  # Verify all 26 tests pass
```

### Phase 2: Create Type Definitions (10 minutes)

Create `types.ts` with `CrudErrorContext` and `ErrorEnhancer` interfaces (see above).

```bash
npm run build  # Must succeed
```

### Phase 3: Extract First Enhancer (30 minutes)

Start with `attribute-enhancer.ts` (self-contained, good learning example):

```typescript
// src/handlers/tool-configs/universal/core/error-enhancers/attribute-enhancer.ts

import type { ErrorEnhancer, CrudErrorContext } from './types.js';
import type { UniversalResourceType } from '../../types.js';

// Copy levenshteinDistance helper (lines 35-64 from original)
const levenshteinDistance = (a: string, b: string): number => {
  // ... complete implementation with signature!
};

// Copy findSimilarAttributes helper (lines 69-83 from original)
const findSimilarAttributes = (
  target: string,
  candidates: string[],
  maxResults: number
): string[] => {
  // ... complete implementation with signature!
};

// Convert enhanceAttributeNotFoundError to enhance function
async function enhance(
  error: unknown,
  context: CrudErrorContext
): Promise<string | null> {
  // ... implementation (lines 93-126 from original)
}

// Add matches function
function matches(error: unknown, _context: CrudErrorContext): boolean {
  const msg = error instanceof Error ? error.message : String(error);
  return /Cannot find attribute with slug\/ID/.test(msg);
}

// Export as ErrorEnhancer
export const attributeNotFoundEnhancer: ErrorEnhancer = {
  name: 'AttributeNotFoundEnhancer',
  matches,
  enhance,
  errorName: 'attribute_not_found',
};
```

Update `index.ts`:

```typescript
export { attributeNotFoundEnhancer } from './attribute-enhancer.js';
export type { ErrorEnhancer, CrudErrorContext } from './types.js';

import type { ErrorEnhancer } from './types.js';
import { attributeNotFoundEnhancer } from './attribute-enhancer.js';

export const CREATE_ERROR_ENHANCERS: ErrorEnhancer[] = [
  attributeNotFoundEnhancer,
];

export const UPDATE_ERROR_ENHANCERS: ErrorEnhancer[] = [
  attributeNotFoundEnhancer,
];
```

Verify:

```bash
npm run build  # Must succeed
npm run test:offline  # All tests must pass
git add .
git commit -m "feat: Extract attribute-not-found enhancer #1001"
```

### Phase 4: Extract Remaining Enhancers (2-3 hours)

Repeat Phase 3 for each enhancer (order matters for pipeline!):

1. **required-fields-enhancer.ts** (check required fields first)
2. **uniqueness-enhancer.ts** (duplicate detection)
3. **select-status-enhancer.ts** (select/status validation)
4. **complex-type-enhancer.ts** (location, phone, personal-name)
5. **record-reference-enhancer.ts** (record reference format)

After **each enhancer**:
- Add to `index.ts` exports
- Add to enhancer arrays (in correct order!)
- `npm run build` - must succeed
- `npm run test:offline` - must pass
- Commit with clear message

### Phase 5: Refactor Main Handlers (1 hour)

Update `crud-error-handlers.ts`:

```typescript
// Add imports
import { CREATE_ERROR_ENHANCERS, UPDATE_ERROR_ENHANCERS } from './error-enhancers/index.js';
import type { CrudErrorContext } from './error-enhancers/types.js';

// KEEP these helpers:
// - createErrorResult
// - extractAttioValidationErrors
// - extractAttioMessage

// REMOVE these (now in enhancers):
// - levenshteinDistance
// - findSimilarAttributes
// - enhanceAttributeNotFoundError
// - enhanceSelectStatusError
// - enhanceComplexTypeError
// - enhanceRecordReferenceError
// - enhanceUniquenessErrorWithSearch
// - buildMissingDealStageMessage

// Replace handleCreateError with pipeline pattern (see code above)
// Replace handleUpdateError with pipeline pattern (see code above)
```

Verify:

```bash
npm run test:offline  # All 26 tests must still pass
wc -l src/handlers/tool-configs/universal/core/crud-error-handlers.ts  # Should be <500
```

---

## ⚠️ Common Pitfalls

### ❌ Pitfall #1: Missing Function Signatures

```typescript
// WRONG - PR #1048 mistake
  const matrix: number[][] = [];  // ❌

// RIGHT
const levenshteinDistance = (a: string, b: string): number => {
  const matrix: number[][] = [];  // ✅
```

### ❌ Pitfall #2: Missing Variable Declarations

```typescript
// WRONG
if (data && typeof data === 'object') {  // ❌ data undefined

// RIGHT
const data = (error.response as Record<string, unknown>).data;  // ✅
if (data && typeof data === 'object') {
```

### ❌ Pitfall #3: Not Capturing enhance() Result

```typescript
// WRONG
for (const enhancer of CREATE_ERROR_ENHANCERS) {
  if (enhancer.matches(error, context)) {
    await enhancer.enhance(error, context);  // ❌ Result lost
    throw createErrorResult(...);  // ❌ What message?
  }
}

// RIGHT
for (const enhancer of CREATE_ERROR_ENHANCERS) {
  if (enhancer.matches(error, context)) {
    const enhanced = await enhancer.enhance(error, context);  // ✅
    if (enhanced) {
      throw createErrorResult(`Failed: ${enhanced}`, ...);  // ✅
    }
  }
}
```

### ❌ Pitfall #4: Wrong Enhancer Order

```typescript
// WRONG - generic enhancers first
export const CREATE_ERROR_ENHANCERS: ErrorEnhancer[] = [
  recordReferenceEnhancer,  // ❌ Too generic
  requiredFieldsEnhancer,   // ❌ Should be first
];

// RIGHT - specific enhancers first
export const CREATE_ERROR_ENHANCERS: ErrorEnhancer[] = [
  requiredFieldsEnhancer,      // ✅ Most specific
  uniquenessEnhancer,
  attributeNotFoundEnhancer,
  complexTypeEnhancer,
  selectStatusEnhancer,
  recordReferenceEnhancer,     // ✅ Most generic
];
```

---

## ✅ Validation Checklist

Before creating PR:

- [ ] All TypeScript files compile (`npm run build`)
- [ ] All 26 existing tests pass (`npm run test:offline`)
- [ ] Line count: `crud-error-handlers.ts` <500 lines (from 1156)
- [ ] Each enhancer has unit tests
- [ ] No linting errors (`npm run lint`)
- [ ] All enhancers exported from `index.ts`
- [ ] Both `CREATE_ERROR_ENHANCERS` and `UPDATE_ERROR_ENHANCERS` defined
- [ ] `handleCreateError` uses enhancer pipeline
- [ ] `handleUpdateError` uses enhancer pipeline
- [ ] Git history is clean with meaningful commits

Code review checklist:

- [ ] Every function has a complete signature
- [ ] Every variable is declared (`const`/`let`/`var`)
- [ ] All imports are present
- [ ] ErrorEnhancer interface consistently implemented
- [ ] Helper functions not duplicated between enhancers
- [ ] Fallback error handling preserved
- [ ] PII sanitization maintained

---

## 📊 Success Criteria

| Metric | Before | Target | 
|--------|--------|--------|
| Total lines | 1156 | <500 |
| handleCreateError | 131 lines | <50 lines |
| handleUpdateError | 127 lines | <50 lines |
| Passing tests | 26 | 26 (zero change) |
| Test coverage | 100% | 100% |

---

## ⏱️ Timeline Estimate

| Phase | Time | 
|-------|------|
| Setup | 15 min |
| Type definitions | 10 min |
| First enhancer | 30 min |
| Remaining enhancers (5×) | 2-3 hours |
| Refactor handlers | 1 hour |
| Testing & validation | 30 min |
| **Total** | **4.5-5.5 hours** |

---

## 🎯 Key Principles

1. **Test after every step** - TypeScript must compile, tests must pass
2. **One enhancer at a time** - Don't extract all at once
3. **Complete function signatures** - Never leave orphaned code blocks
4. **Verify imports** - Every enhancer needs proper imports
5. **Preserve behavior** - Zero functional changes, pure refactoring

---

**Remember**: If TypeScript doesn't compile after a step, **STOP and fix it** before continuing. PR #1048 failed because this rule wasn't followed.
