### ISSUE TITLE
Fix: Critical Regression - Error handler crashes with "enhancedError.getContextualMessage is not a function"

### ISSUE THREAD

**Issue by kesslerio** [kesslerio/attio-mcp-server#425]
### Executive Summary
A critical regression has been discovered after the consolidated fixes in #422 (issues #415, #416, #417). The error handling system now **crashes completely** when dealing with non-existent records or API errors, making the application unusable. Instead of providing helpful error messages, the system throws a fatal error: `enhancedError.getContextualMessage is not a function`.

**Priority**: P0 (Critical - System Breaking)  
**Severity**: CRITICAL - All error handling for universal tools is broken  
**Impact**: Users experience crashes instead of error messages  
**Root Cause**: Incorrect assumption that all errors are EnhancedApiError instances  

---

### Current Behavior (BROKEN)
When any API error occurs (e.g., record not found, validation error), the error handler crashes:

```javascript
// User attempts to get non-existent record
await callTool('get-record-details', {
  resource_type: 'companies',
  record_id: 'non-existent-uuid'
});

// CRASHES with:
TypeError: enhancedError.getContextualMessage is not a function
  at handleGetRecordDetails (/src/handlers/tool-configs/universal/shared-handlers.ts:418)
```

### Expected Behavior
Should return a properly formatted error message:
```json
{
  "isError": true,
  "content": [{
    "type": "text",
    "text": "Record not found: No companies with ID 'non-existent-uuid' exists. Use search-records to find valid companies IDs."
  }]
}
```

---

### Two Different Error Classes Exist
1. **AttioApiError**: Created by Axios interceptor when Attio API returns errors
   - Located in `/src/api/client.ts`
   - Basic error class with message, statusCode, endpoint, method
   - **DOES NOT** have `getContextualMessage()` method

2. **EnhancedApiError**: Created in error handling code for enhanced messages
   - Located in `/src/errors/enhanced-api-errors.ts`
   - Extends AttioApiError
   - **HAS** `getContextualMessage()` method

### The Fatal Assumption
Code at `/src/handlers/tool-configs/universal/shared-handlers.ts` lines 418-422:

```typescript
// BROKEN CODE - Assumes all errors are EnhancedApiError
if (error instanceof AttioApiError) {
  const enhancedError = error as EnhancedApiError;  // WRONG ASSUMPTION!
  return createErrorResult(
    enhancedError.getContextualMessage()  // CRASHES HERE
  );
}
```

### Why This Crashes
1. Attio API returns error (e.g., 404 Not Found)
2. Axios interceptor creates `AttioApiError` instance
3. Error bubbles up to handler
4. Handler incorrectly casts to `EnhancedApiError`
5. Calls non-existent `getContextualMessage()` method
6. **CRASH** - Application terminates with TypeError

---

## 📍 Affected Code Location

**File**: `/src/handlers/tool-configs/universal/shared-handlers.ts`  
**Lines**: 418-422  
**Function**: Error handling in universal tool handlers  

```typescript
// Current broken code
if (error instanceof AttioApiError) {
  const enhancedError = error as EnhancedApiError;  // Unsafe cast
  return createErrorResult(
    enhancedError.getContextualMessage()  // Method doesn't exist
  );
}
```

---

### Option 1: Type Guard Before Method Call
```typescript
if (error instanceof AttioApiError) {
  // Check if it's actually an EnhancedApiError with the method
  if ('getContextualMessage' in error && typeof error.getContextualMessage === 'function') {
    return createErrorResult(error.getContextualMessage());
  } else {
    // Fallback for regular AttioApiError
    return createErrorResult(
      `API Error (${error.statusCode}): ${error.message}`
    );
  }
}
```

### Option 2: Convert AttioApiError to EnhancedApiError
```typescript
if (error instanceof AttioApiError) {
  // Convert regular error to enhanced error
  const enhancedError = error instanceof EnhancedApiError 
    ? error 
    : new EnhancedApiError(
        error.message,
        error.statusCode,
        error.endpoint,
        error.method,
        { /* add context */ }
      );
  
  return createErrorResult(enhancedError.getContextualMessage());
}
```

### Option 3: Unify Error Handling (Recommended)
- Modify Axios interceptor to create EnhancedApiError instances
- OR: Add getContextualMessage() to base AttioApiError class
- Ensures all errors have consistent interface

---

### Critical Requirements
- [ ] Error handler MUST NOT crash when handling API errors
- [ ] All API errors must return formatted error messages
- [ ] Type safety must be enforced (no unsafe casts)
- [ ] Error messages must be helpful and contextual

### Specific Test Cases
- [ ] Non-existent record returns "Record not found" message
- [ ] Invalid UUID returns "Invalid format" message  
- [ ] Validation errors return field-specific guidance
- [ ] Network errors return appropriate retry guidance
- [ ] All error paths tested with integration tests

### Code Quality
- [ ] Proper type guards implemented
- [ ] No assumptions about error instance types
- [ ] Consistent error handling across all universal tools
- [ ] Clear separation between error classes documented

---

## 🧪 Reproduction Steps

1. Start the MCP server
2. Use any universal tool with invalid data:
   ```bash
   # Test with non-existent record
   mcp call-tool get-record-details '{
     "resource_type": "companies",
     "record_id": "11111111-1111-1111-1111-111111111111"
   }'
   ```
3. Observe crash instead of error message

### Expected Result
Error message: "Record not found: No companies with ID..."

### Actual Result  
Crash: "TypeError: enhancedError.getContextualMessage is not a function"

---

## 🔗 Related Issues

- **Caused By**: #422 (Consolidated fixes that introduced EnhancedApiError)
- **Related To**: #415, #416, #417 (Original error handling improvements)
- **Regression From**: Recent "fixes" that broke existing error handling

---

### Investigation Checklist
- [ ] Audit all locations where AttioApiError is created
- [ ] Identify all locations where EnhancedApiError is expected
- [ ] Review Axios interceptor error creation
- [ ] Check all error handling paths in universal tools

### Testing Requirements
- [ ] Unit tests for error type checking
- [ ] Integration tests for all error scenarios
- [ ] Regression tests to prevent future breaks
- [ ] E2E tests for user-facing error messages

### Prevention Measures
- [ ] Add TypeScript strict checks for error handling
- [ ] Implement error handler tests before deployment
- [ ] Document error class hierarchy clearly
- [ ] Add pre-commit hooks for error handling validation

---

## 🚀 Priority Justification

**P0 - CRITICAL** because:
1. **Complete System Failure**: All error handling is broken
2. **User Impact**: Application crashes instead of showing errors
3. **Data Loss Risk**: Users can't understand what went wrong
4. **Regression**: Previously working functionality is now broken
5. **Blocks All Operations**: Every API error causes a crash

**Immediate Action Required**: This blocks all production usage and must be fixed immediately.

---

## 📊 Success Metrics

- [ ] Zero crashes from error handling code
- [ ] 100% of API errors return formatted messages
- [ ] Error message quality maintained from #422 improvements
- [ ] No performance degradation in error handling
- [ ] Full test coverage for error scenarios

**Timeline**: IMMEDIATE - This is a production-blocking issue that requires hotfix deployment.
